OnlineCourse/urls.py
"""
Definition of urls for OnlineCourse.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views


from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()
from django.conf.urls.static import static #импорт функций для настройки доступа к загруженным файлам(и две строчки снизу)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^links$', app.views.links, name='links'),
    url(r'^blog$', app.views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^anketa$', app.views.anketa, name='anketa'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^katalog/', include('shop.urls', namespace='shop')),
    url(r'^registration$', app.views.registration, name='registration'),
    url(r'^newpost$', app.views.newpost, name='newpost'),
    url(r'^videopost$', app.views.videopost, name='videopost'),
    url(r'^users_orders$', app.views.users_orders, name='users_orders'),
    

    
    
   

  
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Войти',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

orders/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User


class Order(models.Model):
    nickname = models.ForeignKey(User, on_delete=models.CASCADE, default=False)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items')
    product = models.ForeignKey(Product, related_name='order_items')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name', 'email', 'address', 'postal_code', 'city']

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # очистка корзины
            cart.clear()
            return render(request, 'orders/order/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'orders/order/create.html',
                  {'cart': cart, 'form': form})

orders/templates/orders/order/create.html
{% extends "app/layout.html" %}

{% block title %}Checkout{% endblock %}

{% block content %}
    <h1>Оформление заказа</h1>
    <div class="order-info">
        <h3>Ваш заказ</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>${{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p>К оплате: ${{ cart.get_total_price }}</p>
    </div>
    <form action="." method="post" class="order-form">
         <p><label for="id_first_name">Имя:</label> <input type="text" name="first_name" maxlength="50" required id="id_first_name" /></p>
        <p><label for="id_last_name">Фамилия:</label> <input type="text" name="last_name" maxlength="50" required id="id_last_name" /></p>
        <p><label for="id_email">Email:</label> <input type="email" name="email" maxlength="254" required id="id_email" /></p>
        <p><label for="id_address">Адрес:</label> <input type="text" name="address" maxlength="250" required id="id_address" /></p>
        <p><label for="id_postal_code">Почтовый индекс:</label> <input type="text" name="postal_code" maxlength="20" required id="id_postal_code" /></p>
        <p><label for="id_city">Город:</label> <input type="text" name="city" maxlength="100" required id="id_city" /></p>
        <p><input type="submit" value="Оплатить заказ"></p>
        {% csrf_token %}
    </form>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "app/layout.html" %}

{% block title %}Спасибо{% endblock %}

{% block content %}
    <h1>Спасибо за заказ</h1>
    <p>Ваш заказ был завершен успешно.
        </p>
{% endblock %}