OnlineCourse/urls.py
"""
Definition of urls for OnlineCourse.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views


from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()
from django.conf.urls.static import static #импорт функций для настройки доступа к загруженным файлам(и две строчки снизу)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^links$', app.views.links, name='links'),
    url(r'^blog$', app.views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^anketa$', app.views.anketa, name='anketa'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^katalog/', include('shop.urls', namespace='shop')),
    url(r'^registration$', app.views.registration, name='registration'),
    url(r'^newpost$', app.views.newpost, name='newpost'),
    url(r'^videopost$', app.views.videopost, name='videopost'),
    url(r'^users_orders$', app.views.users_orders, name='users_orders'),
    

    
    
   

  
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Войти',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}{% load staticfiles %}

<div class="container">
		
        <div class="title_pol">
				<h1>О нас</h1>
				<p>Пекарня "Жаровня" основана в 2016 году, в городе Пскове, занимаемся производством и продажей сдобной, глазированной и слоёной выпечки. Для на качество товара и обслуживания приоритет.</p>
        </div>


       
</div>



		
		
{% endblock %}

app/templates/app/anketa.html
{% extends "app/layout.html" %}

<div class="container body-content">


      
{% block content %}
{% if form != None %}
<br><h2> Отправьте пожалуйста заполненную анкету </h2></br>
    <div>
        <form method ="POST">
        {% csrf_token %}
        <label for=" {{ form.name.id_for_label}}" > {{form.name.label}}:</label>
        {{form.name}} <br><br>
        <label for="{{form.city.id_for_label}}">{{form.city.label}}:</label>
        {{form.city}}<br><br>
         <label for=" {{form.gender.id_for_label}}">{{form.gender.label}}:</label>
        {{form.gender}}<br><br>
        <label for=" {{form.job.id_for_label}}">{{form.job.label}}:</label>
        {{form.job}}<br><br>
        <label for=" {{form.internet.id_for_label}}">{{form.internet.label}}:</label>
        {{form.internet}}<br><br>
        <label for=" {{form.notice.id_for_label}}">{{form.notice.label}}:</label>
        {{form.notice}}<br><br>
        <label for=" {{form.email.id_for_label}}">{{form.email.label}}:</label>
        {{form.email}}<br><br>
        <label for=" {{form.message.id_for_label}}"><br><br><br><br><br>{{form.message.label}}:</label>
        {{form.message}}<br><br>
        <input type="submit" value="Отправить">
        </form>
    </div>
{% else %}
<br><h2>Благодарим за отправленную форму</h2>
    <h3>Вы рассказали нам о себе следующее:</h3>
<ul>
    <li><span>Имя:</span>{{data.name}}</li>
    <li><span>Город:</span>{{data.city}}</li>
    <li><span>Пол:</span>{{data.gender}}</li>
    <li><span>Работа:</span>{{data.job}}</li>
    <li><span>В интернете:</span>{{data.internet}}</li>
    <li><span>Получать новости с сайта на e-mail:</span>{{data.notice}}</li>
    <li><span>Ваш e-mail:</span>{{data.email}}</li>
    <li><span>Информация о себе:</span>{{data.message}}</li>
</ul>
{% endif %}
{% endblock %}


        


</body>
</html>

app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}
<div class="title_page">
<h2>{{title}}</h2>
</div>
{% for post in posts %}
<div class="blog_page_display">
<div class="blog_page">
    <h2>{{post.title}}</h2>
    <p>{{post.description}}</p>
    <h4>{{post.posted}}</h4>
    <p><a href="{% url 'blogpost'  parametr=post.id %}">Читать далее</a></p>
</div>
 </div>
 <hr />
{% endfor %}

{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}
{% block content %}
{% load staticfiles %}
<h2>{{post_1.title}}</h2>
{% if post_1.image and post_1.image.url != "/media/temp.jpg" %}
    <img src="{{post_1.image.url}}" alt="Картинка" width="300" height=" 200" />
{% endif %}

{% autoescape off %}
<p> {{ post_1.content|linebreaksbr }} </p>
{% endautoescape %}


{% if user.is_authenticated %}
    <h3>Добавить комментарий</h3>
    <form method="POST">
        {% csrf_token %}
        <div>
            {{form.as_p}}
            <button type="submit" class="save btn btn-default">Отправить комментарий</button>
        </div>
    </form>
{% else %}
    <h3>Для добавления комментария,авторизуйтесь.</h3>
{% endif %}

<div class="comment">
{% for comment in comments %}

<h5>{{comment.author}}</h5>
<h4>{{comment.text|linebreaksbr}}</h4>
<h7>{{comment.date}}</h7>
{% endfor %}
</div>
<br><br />

<p><a href="{% url 'blog' %}">Назад</a></p>
{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}


<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">

    <ol class="carousel-indicators">

       <!--<li data-target="#myCarousel" data-slide-to="0" class="active"></li>--> 

        <li data-target="#myCarousel" data-slide-to="1" class="active"></li>

        <li data-target="#myCarousel" data-slide-to="2"></li>

        <li data-target="#myCarousel" data-slide-to="3"></li>

    </ol>

    <div class="carousel-inner" role="listbox">

        <div class="item active">

            <img src="{% static 'app/content/product/1.jpg'%} " alt="Первый слайд" class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>
                    Песочный пирог
                    

                    <a class="btn btn-default" href="https://www.iamcook.ru/showrecipe/13258">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

        <div class="item">

            <img src="{% static 'app/content/product/3.jpg'%} " alt="Второй слайд"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                   Маффины с ягодами 

                    <a class="btn btn-default" href="https://vku.life/maffiny-recept-s-foto/">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

        <div class="item">

            <img src=" {% static 'app/content/product/2.jpg'%} " alt="Третий слайд"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                  Круассаны с начинкой

                    <a class="btn btn-default" href="https://povar.ru/recipes/kruassany_s_nachinkoi-48830.html">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">

        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>

        <span class="sr-only">Previous</span>

    </a>

    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">

        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

        <span class="sr-only">Next</span>

    </a>

</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - </title>
    {% load staticfiles %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&family=Montserrat:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <a href="/" class="navbar-brand"> <img src="{% static 'app/content/L.png' %}" alt="logo" /> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'shop:product_list' %}">Каталог</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <!--<li><a href="{% url 'links' %}">Партнеры</a></li>-->
                    <li><a href="{% url 'blog' %}">Новости</a></li>
                    <!--<li><a href="{% url 'anketa' %}">Связаться</a></li>-->
                    {% if user.is_superuser %}
                    <li><a href="admin/app/blog/add/">Добавить новость</a></li>
                    <li><a href="admin/shop/product/add" >Товар</a></li>
                    {% endif %}
                    <!--<li><a href="{% url 'videopost' %}">Видео</a></li>-->
                    {% if not user.is_authenticated %}
                    <li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                    {% if user.is_staff %}
                    <li>
                    <a href="{% url 'users_orders' %}">Заказы</a>
                    </li>
                    {% endif %}
                   
                    
   
                    
                </ul>
               {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
       
        <footer 

	    </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/links.html
{% extends "app/layout.html" %}
    
{% block content %}{% load staticfiles %}
       

      <div class="images">
          <div class="client1">
      <a href ="https://www.biomechatronics.ca/" target="_blank"> <img src="{% static 'app/content/product/4.jpg' %}" alt="Logo 1"/></a>
          <p>Adidas (немецкий: [adiˌdas]; стилизованно под adidas с 1949 года) — немецкая транснациональная компания по производству спортивной одежды, обуви и аксессуаров. Это крупнейший производитель спортивной одежды в Европе и второй по величине в мире после Nike. Это холдинговая компания для Adidas Group, которая состоит из Reebok и Runtastic. Выручка Adidas за 2018 год составила 21,915 миллиарда евро.</p></div>
      <div class="client2">
          <a href ="https://www.utwente.nl/" target="_blank"> <img src="{% static 'app/content/product/6.jpg' %}" alt="Logo 2"/></a>
          <p>Nike (['naɪkɪ], «Найк») — американская транснациональная компания, специализирующаяся на спортивной одежде и обуви. Штаб-квартира — в городе Бивертон (штат Орегон). Почти вся продукция Nike производится сторонними компаниями-подрядчиками вне территории США (в основном в Азии), сама компания является правообладателем торговых марок, разрабатывает дизайн продукции и владеет сетью магазинов (около 1150 по всему миру), а также торговых центров NikeTown. С 20 сентября 2013 года входит в Промышленный индекс Доу Джонса. Nike является самым дорогим спортивным брендом в мире (по мнению Forbes).</p></div>
      <div class="client3">
          <a href ="https://www.autodesk.com/" target="_blank"> <img src="{% static 'app/content/product/5.jpg' %}" alt="Logo 3"/></a>
          <p>"Reebok International Limited (ˈriːbɒk) — американская компания по производству спортивной одежды, обуви и аксессуаров. Штаб-квартира расположена в Бостоне (штат Массачусетс). С 2005 года является дочерним подразделением компании Adidas. Reebok производит и распространяет спортивную одежду для фитнеса, бега и кроссфита, включая аксессуары и обувь. Это официальный спонсор обуви и одежды для CrossFit и Spartan Race.</p></div>
      </div>

      
   
{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте созданный аккаунт для входа.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Логин</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Введите корректный логин или пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'cart:cart_detail' %}">Корзина</a></li>
</ul>


<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand"></span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Войти</a></li>
</ul>

{% endif %}

app/templates/app/my_orders.html
 
{% extends 'app/layout.html' %}


{% block content %}


<table>
<tr>
<td colspan="2">Вы заказывали товар</td>


<td colspan="2">На сумму</td>

<td colspan="2">Дата заказа</td>
</tr>
{% for order in orders %}
{% for item in order_item %}



<tr>
<td colspan="2"><b>{{item.product}}</b></td>
    <td colspan="2"><b>{{item.price}}</b></td>
<td colspan="2"><b>{{order.created}}</b></td>

</tr>

{% endfor %}
    {% endfor %}

</table>

</div>
</div>









{% endblock %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}

{% block content %}
<h3>Добавить статью.</h3>

<form method="POST" enctype="multipart/form-data" > {% csrf_token %}
    <div>
    {{blogform.as_p}}
    <button type="submit" class="save btn btn-default">Сохранить статью</button>
    </div>
 </form>   

{% endblock %}

app/templates/app/registration.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    {% extends "app/layout.html" %}

{% block content %}

<h2>Регистрация пользователя</h2>

<form method="POST" > {% csrf_token %}

<div>

{{ regform.as_p}}

<button type="submit" class="save btn btn-default" > Зарегистрировать </button>

</div>

</form>

{% endblock %}
</body>
</html>

app/templates/app/users_orders.html
{% extends 'app/layout.html' %}


{% block content %}




<a href="admin/orders/order" >Перейти к редактированию заказов</a>



<table>
<tr>
<td colspan="2">id Заказа</td>




<td colspan="2">email</td>
<td colspan="2">Город</td>
<td colspan="2">Почтовый индекс</td>
<td colspan="2">Дата заказа</td>
<td colspan="2">Статус оплаты</td>

</tr>
{% for order in users_orders %}




<tr>
<td colspan="2"><b>{{order.id}}</b></td>
<td colspan="2"><b>{{order.email}}</b></td>

<td colspan="2"><b>{{order.city}}</b></td>
<td colspan="2"><b>{{order.postal_code}}</b></td>

<td colspan="2"><b>{{order.created}}</b></td>
{% if order.paid %}
<td colspan="2"><b>Оплачен</b></td>
{% else %}
<td colspan="2"><b>Не оплачен</b></td>
{% endif %}


</tr>

{% endfor %}


</table>

{% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}

{% block content %}

<div class="container">
    <h1>Видео по нашей тематике</h1>
<div class=" video_page">
<div>

 
<video src="/media/2.mp4" class="videos" controls="controls" width="800" height="600" poster="/media/2.jpg">
</video>
    </div>
</div>
<div>
    <video src="/media/1.mp4"  class="videos" controls="controls" width="800" height="600" poster="/media/1.jpg">
</video>
</div>
</div>






{% endblock %}